name: CI/CD for MyApp

on:
  push:
    branches: [ main, dev, test, stage ]

jobs:
  build-deploy:
    uses: joshisu/reusable_workflow/.github/workflows/dot-net.yml@main
    secrets: inherit
    with:
      project_path: SampleWebApp.csproj
      build_config: Release
      app_name: ${{ github.ref == 'refs/heads/main' && 'demowebapp' || github.ref == 'refs/heads/stage' && 'demo-web28' || github.ref == 'refs/heads/test' && 'your-webapp-dev' || 'your-webapp-dev' }}
      environment: ${{ github.ref_name }}
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}